### ISSUE TITLE
百度翻译API翻译失败

### ISSUE THREAD

**Issue by ElainaFanBoy** [maoxig/nonebot-plugin-manga-translator#1]
Bot:翻译完成,当前api:无可用API
Bot:翻译失败,错误信息见控制台输出

05-24 19:23:42 [WARNING] nonebot_plugin_manga_translator | API[baidu]不可用：尝试切换下一个
05-24 19:23:45 [WARNING] nonebot_plugin_manga_translator | 翻译失败:ActionFailed(data=None, echo='18', message='empty message', msg='SEND_MSG_API_ERROR', retcode=100, status='failed', wording='empty message')

本来一直使用正常的，好像是这两天就突然不行了，看了眼API应该没问题的，没动过也没欠费

**Comment by ElainaFanBoy** [comment]
> 经测试，无论上传什么图片，返回字段都是
> `{
>     "error_code": "69002",
>     "error_msg": "picture recognition time out"
> }`
> 这样同时也导致响应超时了，所以可能是百度api故障，过几天再试试吧，或者先用别的api

了解了，大佬辛苦喵！

**Comment by ElainaFanBoy** [comment]
> > > 经测试，无论上传什么图片，返回字段都是
> > > `{ "error_code": "69002", "error_msg": "picture recognition time out" }`
> > > 这样同时也导致响应超时了，所以可能是百度api故障，过几天再试试吧，或者先用别的api
> > 
> > 了解了，大佬辛苦喵！
> 
> 现在api貌似修好了，你可以试试现在能用吗

确实可以了，是官方那边的问题吗

**Comment by maoxig** [comment]
> > > > 经测试，无论上传什么图片，返回字段都是
> > > > `{ "error_code": "69002", "error_msg": "picture recognition time out" }`
> > > > 这样同时也导致响应超时了，所以可能是百度api故障，过几天再试试吧，或者先用别的api
> > > 
> > > 
> > > 了解了，大佬辛苦喵！
> > 
> > 
> > 现在api貌似修好了，你可以试试现在能用吗
> 
> 确实可以了，是官方那边的问题吗

估计是百度抽风了
