### ISSUE TITLE
百度API配置出错

### ISSUE THREAD

**Issue by YipSzeho** [maoxig/nonebot-plugin-manga-translator#2]
![c546a84dd901e151d9e8201a67219bce](https://github.com/user-attachments/assets/917a4e1c-f114-439f-86ef-f7a4457b9c3c)

**Comment by maoxig** [comment]
写在.env文件里的`baidu_app_id
`和`baidu_app_key`应为`str`型，例如`baidu_app_id="114514"`，请注意要带引号，否则会被识别成`int`型导致类型不匹配

**Comment by YipSzeho** [comment]
奇怪了，已经带上引号了的
![image](https://github.com/user-attachments/assets/21e29e7c-4fdd-4ca6-8eb9-d957e93300df)

**Comment by maoxig** [comment]
这就奇怪了，而且即使这里输入是整型，pydantic应该也会自动做类型转换的。也许是nb新版本或者别的导致的特性吧，晚会我会测试一下，看能不能修复这个问题

**Comment by maoxig** [comment]
![image](https://github.com/user-attachments/assets/feb6e832-e4d2-4829-b304-71127cdc051b)
这是`nonebot`在`pydantic V2`下出现的问题，在`pydantic V1`下则不会出现。不过我已经兼容`pydantic V2`而且发版了，你只需更新本插件即可解决该问题。

~~未来如果有别的插件出现同样问题，插件作者又不更新的话，可以降级`pydantic`来解决~~
