### ISSUE TITLE
翻译失败:'render_image'

### ISSUE THREAD

**Issue by Qyyxzz** [maoxig/nonebot-plugin-manga-translator#3]
这个是什么原因呢大佬
![3006603a8886abc7829131c468156c31](https://github.com/user-attachments/assets/6567b13c-62b7-4a33-9512-e3efa55a1773)
![6947ab3e00dbb9c2c476e29d884a7d4b](https://github.com/user-attachments/assets/cfd2b36a-11d1-4c36-ae1d-90df920080c4)
![image](https://github.com/user-attachments/assets/66490888-938d-44cc-b1ac-9af81bf42f82)
都亲测可用

**Comment by maoxig** [comment]
插件没对API填写的合法性做校验，如果没有申请有道翻译的API，就不用填进去，不然会尝试调用有道翻译api，导致返回失败。

你把没用的apikey删掉应该就可以了。

不过这里的报错信息确实不够明显，过段时间会考虑完善一下。

**Comment by maoxig** [comment]
> > 插件没对API填写的合法性做校验，如果没有申请有道翻译的API，就不用填进去，不然会尝试调用有道翻译api，导致返回失败。
> > 
> > 你把没用的apikey删掉应该就可以了。
> > 
> > 不过这里的报错信息确实不够明显，过段时间会考虑完善一下。
> 
> okok 感谢大佬这回可以了 话说大佬知道什么修复比较好吗（）现在嵌字修复坑洼有点严重 之前用BallonsTranslator忘了什么配置了）

不太了解，不过我刚刚看了似乎BallonsTranslator用的是aot_inpainter

https://github.com/dmMaze/BallonsTranslator/blob/dev/modules/inpaint/aot.py

仅供参考。

**Comment by maoxig** [comment]
> > > > 插件没对API填写的合法性做校验，如果没有申请有道翻译的API，就不用填进去，不然会尝试调用有道翻译api，导致返回失败。
> > > > 你把没用的apikey删掉应该就可以了。
> > > > 不过这里的报错信息确实不够明显，过段时间会考虑完善一下。
> > > 
> > > 
> > > okok 感谢大佬这回可以了 话说大佬知道什么修复比较好吗（）现在嵌字修复坑洼有点严重 之前用BallonsTranslator忘了什么配置了）
> > 
> > 
> > 不太了解，不过我刚刚看了似乎BallonsTranslator用的是aot_inpainter
> > https://github.com/dmMaze/BallonsTranslator/blob/dev/modules/inpaint/aot.py
> > 仅供参考。
> 
> ok 麻烦回复了

抱歉，也许是lama_large，参考这次https://github.com/dmMaze/BallonsTranslator/commit/3fa1ef97543d934ae1142435c4422eef6c273510提交设成了默认inpainter，不过我对BallonsTranslator了解不多
