### ISSUE TITLE
发送图片失败（?）

### ISSUE THREAD

**Issue by Qyyxzz** [maoxig/nonebot-plugin-manga-translator#4]
![8b11a2a43f5dfe65deca4934c407ca89](https://github.com/user-attachments/assets/491fa1fd-4df9-4de1-b154-bf84347d46a3)
![b7274490f9dcb028031c95da4a9b53e0](https://github.com/user-attachments/assets/a848e071-e06a-4474-9f81-970e688c9b7b)
用了--upscaler=waifu2x --upscale-ratio=2参数来放大之后 图片大小明显大了不少 但是试了都没有超过10mb几mb左右，大概是第一次发送的时候失败了？有接收到第二次请求就返回了 不过没有用这参数也有低概率会这样 这是什么原因呢 如果是协议端原因就打扰了（）
然后下面是参数
![image](https://github.com/user-attachments/assets/a66df3a2-45ee-4af9-8a23-b3953c733cee)
![image](https://github.com/user-attachments/assets/8eaacefb-6b3c-4eec-937a-11b61319f2c4)

不知道env写的是不是有问题试了没效果 我就去config.py直接写进去了（）

**Comment by maoxig** [comment]
`.env`没加载可能是填写或者环境变量加载的问题，nb启动的时候会打印所有的环境变量，你可以检查一下。插件也会在启动的时候打印已加载的数据。

图片发送失败应该是协议端的问题，比如图片太大发送超时等，可以尝试更新协议端、qq版本等。

**Comment by Qyyxzz** [comment]
> `.env`没加载可能是填写或者环境变量加载的问题，nb启动的时候会打印所有的环境变量，你可以检查一下。插件也会在启动的时候打印已加载的数据。
> 
> 图片发送失败应该是协议端的问题，比如图片太大发送超时等，可以尝试更新协议端、qq版本等。
更新了napcat最新版本之后发现还是没用 然后经过测试之后发现是format=png 输出图片为png格式的问题 去掉了这个参数就正常了
